### PR TITLE
Use global video context instead a saved one

### PR DESCRIPTION
**Pull request by RodrigoHolztrattner**
Asana ticket: https://app.asana.com/0/734357654754972/1107706265898330/f

Fix the bug of retrieving wrong values for skipped frames and an idle crash related to calling its method.

### CODE REVIEW

**Review by summeroff — APPROVED** [review]

**Review by EddyGharbi — CHANGES_REQUESTED** [review]
Good job finding this and fixing it! 

Only thing is that I'm a not a big fan of leaving deprecated code considering our past. If we're not careful we end up with a considerable amount of dead code within weeks. I would remove it and create a PR in the frontend along with the update of the module that uses the new API.

**Comment by RodrigoHolztrattner** [comment]
Working on it!

**Comment by RodrigoHolztrattner** [comment]
Changes done, frontend PR: https://github.com/stream-labs/streamlabs-obs/pull/1363

**Review by EddyGharbi — APPROVED** [review]
Ty, looks good 👍

**Pull request merged**
