### PR TITLE
Update libobs to v28.2.24

### PR DESCRIPTION
**Pull request by EddyGharbi**
EddyGharbi	Merge pull request #468 from stream-labs/merge-obs28.0.3
Eddy Gharbi	Merge branch 'streamlabs' of github.com:stream-labs/obs-studio into merge-obs28.0.3
EddyGharbi	Merge pull request #472 from stream-labs/fix-invalid-version
Eddy Gharbi	CI: fix invalid OBS version on mac
Eddy Gharbi	CI: fix invalid OBS version
Eddy Gharbi	Merge tag '28.0.3' of https://github.com/obsproject/obs-studio into merge-obs28.0.3
jpark37	win-wasapi: Fix Stop hang
Matt Gajownik	frontend-tools: Display dialog when changing Python version
Matt Gajownik	frontend-tools: Display Python version in UI
PatTheMav	UI: Fix AutoRemux not working when FFmpeg output configured
jpark37	win-wasapi: Don't reconnect when inactive
jp9000	libobs: Update version to 28.0.3
Exeldro	obs-scripting: Fix compile when python is not found
jp9000	obs-ffmpeg: Fix unpause causing certain encoders to fail
jp9000	libobs: Add function to get encoder pause offset
gxalpha	UI: Don't reselect SceneTree items if tree is clearing
derrod	UI: Remove executable bit from public key file
shinji3	obs-ffmpeg: Fix m3u8 recording in AMF
Aleix Pol	linux-pipewire: Close sessions as we are done with them
jpark37	libobs/media-io: Restore color range conversion
Matt Gajownik	CI: Downgrade Sphinx to fix docs build error
jpark37	libobs/media-io: Avoid scaler for range diff
Kurt Kartaltepe	linux-capture: Fixup window name/class checking
Ryan Foster	obs-ffmpeg: Cap AMF encoder at 100 Mbps
cg2121	UI: Fix color of popout icon
cg2121	UI: Fix dock titlebar icons not loading

### CODE REVIEW

**Comment by hangai247** [comment]
@EddyGharbi 
Hi, I am seeing a lot of your active contribution to this project and we're really thankful for you guys developing such a great native OS library. Forgive me for raising another matter here. We're trying to use this library for our ElectronJS project but having a compile-time error on M1 Macs when we try MacOS build as mentioned in this [issue](https://github.com/stream-labs/obs-studio-node/issues/911). `mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')` We dug through this repo for a while and could NOT find any reference regarding M1 Macs. Could you let us know if you have a reference regarding this? Thank you. 🙏🙇🏻‍♂️

**Comment by EddyGharbi** [comment]
Thank you for your interest in our project, we are glad to hear that you find our work useful.

We are still working on supporting native compilation on Mac M1, it is currently no building there. I'll be sure to update you on the issue you linked when we support it

**Comment by hangai247** [comment]
@EddyGharbi Thank you for your quick response. We're really sorry to hear that it is NOT supporting native compilation on Mac M1. But do we have any workaround for making the ElectronJS app built on Intel Macs? The reason why I am asking is that the desktop application built https://github.com/stream-labs/desktop using this library works on M1 Macs. Could you explain how it is working and how we can do the same for our app?

**Comment by EddyGharbi** [comment]
You can run apps built for the Intel arch on Mac M1 through Rosetta. The ElectronJS app (Streamlabs Desktop) is built on Mac Intel and can be ran on Mac M1. We unfortunately don't have any workarounds right now to build natively on M1.

**Pull request merged**
