### PR TITLE
Fix fader volmeter module generation

### PR DESCRIPTION
**Pull request by RodrigoHolztrattner**
This PR is an attempt to fix how the V8 library is generating the modules for these 2 classes, it seems that it is not being able to proper generate the code and it could cause some crashes when creating/deleting an object from them. It's probably related to our old V8 library usage.

Update1: The current implementation will make the unity tests work.
Update2: This PR is frozen until we decide if it's a good approach to resolve this error.

### CODE REVIEW

**Review by pdamasceno — APPROVED** [review]
We already discussed this extensively. Everything is ok now that we are not using a unique pointer in these cases.

**Comment by EddyGharbi** [comment]
What's the status on this?

**Comment by RodrigoHolztrattner** [comment]
Fixed the conflicts. This will allow our tests to pass and I added a task on Asana to review it in the future https://app.asana.com/0/734357654754972/1108852507583058/f

**Comment by EddyGharbi** [comment]
Looks good 👍

**Pull request merged**
